import { Platform, Niche, PLATFORM_GRADIENTS, PLATFORM_EMOJIS, NICHE_EMOJIS } from "./utils";

export interface Listing {
  id: string;
  platform: Platform;
  username: string;
  niche: Niche;
  followers: number;
  monthly_income: number;
  engagement_rate: number;
  price: number;
  minimum_offer: number;
  status: "active" | "pending" | "sold";
  verified_income: boolean;
  tiktok_shop_eligible: boolean;
  monetized: boolean;
  location: string;
  description: string;
  seller_name: string;
  seller_id: string;
  seller_rating: number;
  seller_sales: number;
  created_at: string;
  featured: boolean;
  gradient: string;
  emoji: string;
  niche_emoji: string;
}

const LISTINGS_DATA: Omit<Listing, "gradient" | "emoji" | "niche_emoji">[] = [
  // ── TikTok ─────────────────────────────────────────────────────────────────
  { id:"listing-0",  platform:"TikTok",    username:"@fitnessdaily",      niche:"Fitness",   followers:850000,  monthly_income:4200,  engagement_rate:9.2,  price:85000,  minimum_offer:70000,  status:"active", verified_income:true,  tiktok_shop_eligible:true,  monetized:true,  location:"United States", description:"Top fitness account with loyal 18-35 demographic. 3 active brand deals. TikTok Shop enabled with $2K/mo shop revenue. 60% US audience.",                          seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-10T10:00:00Z", featured:true  },
  { id:"listing-1",  platform:"TikTok",    username:"@cryptoking2024",    niche:"Crypto",    followers:420000,  monthly_income:2100,  engagement_rate:7.8,  price:42000,  minimum_offer:35000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United Kingdom", description:"Crypto/finance niche. Highly engaged 25-40 audience. Newsletter of 12K included. 4 years of content history with zero violations.",                          seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-15T12:00:00Z", featured:true  },
  { id:"listing-2",  platform:"TikTok",    username:"@beautyqueenxo",     niche:"Beauty",    followers:1200000, monthly_income:7800,  engagement_rate:11.4, price:156000, minimum_offer:130000, status:"active", verified_income:true,  tiktok_shop_eligible:true,  monetized:true,  location:"United States", description:"Premium beauty account with 7 active brand deals. UGC rate: $3K/post. Female 18-24 audience 78%. Shop GMV $2.5K/month. Transferable contracts.",                   seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-08T09:00:00Z", featured:true  },
  { id:"listing-3",  platform:"TikTok",    username:"@gamingpro_hq",      niche:"Gaming",    followers:250000,  monthly_income:1200,  engagement_rate:8.5,  price:24000,  minimum_offer:20000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,  location:"Canada",        description:"Gaming account focused on FPS/battle royale. Consistent 200K+ monthly views. Clean account with strong 16-24 male demographic.",                                   seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-20T14:00:00Z", featured:false },
  { id:"listing-4",  platform:"TikTok",    username:"@travelvibes_co",    niche:"Travel",    followers:380000,  monthly_income:1900,  engagement_rate:6.9,  price:38000,  minimum_offer:32000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Australia",     description:"Luxury travel niche. Hotel, airline, and travel gear brand deals. 40% international audience. 3.2M total likes.",                                                 seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-12T11:00:00Z", featured:false },
  { id:"listing-5",  platform:"TikTok",    username:"@foodielife_us",     niche:"Food",      followers:620000,  monthly_income:3100,  engagement_rate:10.2, price:62000,  minimum_offer:52000,  status:"active", verified_income:true,  tiktok_shop_eligible:true,  monetized:true,  location:"United States", description:"Food and recipe content. Viral recipe format with 50M+ total views. DoorDash and HelloFresh sponsored posts history. Active affiliate links.",                      seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-05T08:00:00Z", featured:true  },
  { id:"listing-6",  platform:"TikTok",    username:"@techtalks_daily",   niche:"Tech",      followers:310000,  monthly_income:2400,  engagement_rate:7.1,  price:48000,  minimum_offer:40000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Tech reviews and news. Strong affiliate revenue from Amazon and Best Buy. High-intent buyer demographic (25-45 male).",                                          seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-18T16:00:00Z", featured:false },
  { id:"listing-7",  platform:"TikTok",    username:"@luxeliving_now",    niche:"Lifestyle", followers:490000,  monthly_income:2800,  engagement_rate:8.8,  price:56000,  minimum_offer:47000,  status:"active", verified_income:false, tiktok_shop_eligible:true,  monetized:true,  location:"United States", description:"Luxury lifestyle. Watch, fashion, and home décor brands. Aspirational content with premium demographics. 65% female 25-40.",                                     seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-22T10:00:00Z", featured:false },
  { id:"listing-8",  platform:"TikTok",    username:"@moneyminds_app",    niche:"Finance",   followers:720000,  monthly_income:5400,  engagement_rate:6.3,  price:108000, minimum_offer:90000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Personal finance and investing. 720K engaged followers. Credit card and brokerage affiliate deals pay $8-15 per conversion. High CPM niche.",                   seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-03T09:00:00Z", featured:true  },
  { id:"listing-9",  platform:"TikTok",    username:"@sportsnation_hq",   niche:"Sports",    followers:560000,  monthly_income:2600,  engagement_rate:9.7,  price:52000,  minimum_offer:44000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,  location:"United Kingdom", description:"Sports highlights and commentary. Peak engagement during premier league season. Sportsbook sponsor history. Strong UK male 18-35 demographic.",               seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-14T13:00:00Z", featured:false },
  // ── Instagram ──────────────────────────────────────────────────────────────
  { id:"listing-10", platform:"Instagram", username:"@glowupguru",        niche:"Beauty",    followers:520000,  monthly_income:3800,  engagement_rate:4.2,  price:95000,  minimum_offer:80000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Beauty & skincare IG. 4 brand deals/month. Reels avg 500K+ views. Very high saved-post rate great for product discovery. Transferable brand relationships.",       seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-07T11:00:00Z", featured:true  },
  { id:"listing-11", platform:"Instagram", username:"@wanderlust.jane",   niche:"Travel",    followers:290000,  monthly_income:2200,  engagement_rate:3.8,  price:52800,  minimum_offer:45000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Germany",       description:"Authentic travel storytelling. Reels getting 500K+ views. Weekly hotel partnership emails. Clean account history, 5 years old.",                                   seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-19T15:00:00Z", featured:false },
  { id:"listing-12", platform:"Instagram", username:"@gymrat_official",   niche:"Fitness",   followers:740000,  monthly_income:5200,  engagement_rate:5.1,  price:124800, minimum_offer:105000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Bodybuilding & fitness. Whoop, MyProtein, Gymshark partnership history. Very high CPM for fitness. Male 22-35 90% audience.",                                  seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-02T08:00:00Z", featured:false },
  { id:"listing-13", platform:"Instagram", username:"@foodies.co",        niche:"Food",      followers:180000,  monthly_income:900,   engagement_rate:6.3,  price:18000,  minimum_offer:15000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"France",        description:"Food photography and restaurant reviews. Paris-based with strong local brand deal potential. Growing 5K followers/month organically.",                             seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-25T10:00:00Z", featured:false },
  { id:"listing-14", platform:"Instagram", username:"@cryptoboss_ig",     niche:"Crypto",    followers:95000,   monthly_income:2800,  engagement_rate:3.2,  price:67200,  minimum_offer:55000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"UAE",           description:"Crypto/DeFi account. 95K engaged crypto investors. Paid newsletter of 8K included. Project partnership rates: $2K-10K per post.",                               seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-09T12:00:00Z", featured:false },
  { id:"listing-15", platform:"Instagram", username:"@businessmind_co",   niche:"Business",  followers:210000,  monthly_income:3600,  engagement_rate:4.8,  price:86400,  minimum_offer:72000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Business and entrepreneurship content. Highly engaged founder audience. Course sales convert at 3.2%. SaaS tool affiliate deals.",                           seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-16T14:00:00Z", featured:false },
  { id:"listing-16", platform:"Instagram", username:"@musicfanatic_hq",   niche:"Music",     followers:340000,  monthly_income:1700,  engagement_rate:5.5,  price:34000,  minimum_offer:28000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"United States", description:"Music discovery and reviews. Strong 18-28 demographic. Spotify and Apple Music affiliate revenue. Concert ticket partnership potential.",                       seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-21T09:00:00Z", featured:false },
  { id:"listing-17", platform:"Instagram", username:"@healthylife_now",   niche:"Fitness",   followers:450000,  monthly_income:2900,  engagement_rate:4.6,  price:69600,  minimum_offer:58000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Canada",        description:"Healthy lifestyle and wellness. Yoga, nutrition, mindfulness content. 80% female 25-40. Strong supplement and wellness brand deal history.",                      seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-11T11:00:00Z", featured:false },
  { id:"listing-18", platform:"Instagram", username:"@techreview_daily",  niche:"Tech",      followers:165000,  monthly_income:2100,  engagement_rate:3.9,  price:50400,  minimum_offer:42000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Tech reviews and unboxings. Amazon Associates avg $1.8K/mo. High purchase-intent audience. Strong engagement on product posts.",                              seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-17T15:00:00Z", featured:false },
  { id:"listing-19", platform:"Instagram", username:"@gaming_world_gg",   niche:"Gaming",    followers:280000,  monthly_income:1400,  engagement_rate:5.8,  price:28000,  minimum_offer:23000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"Brazil",        description:"Gaming lifestyle account. Growing fast in Latin America market. Peripheral and headset brand deal potential. Strong 16-25 male demographic.",                     seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-23T12:00:00Z", featured:false },
  // ── YouTube ────────────────────────────────────────────────────────────────
  { id:"listing-20", platform:"YouTube",   username:"FitnessUnlocked",    niche:"Fitness",   followers:320000,  monthly_income:4800,  engagement_rate:5.8,  price:115200, minimum_offer:95000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"320K subscriber fitness channel. AdSense $2.8K/mo + sponsorships $2K/mo. Evergreen workout content. CPM avg $14. Strong 25-40 demographic.",                  seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-06T10:00:00Z", featured:true  },
  { id:"listing-21", platform:"YouTube",   username:"CryptoWeekly",       niche:"Finance",   followers:180000,  monthly_income:8400,  engagement_rate:4.1,  price:201600, minimum_offer:170000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United Kingdom", description:"Finance/crypto YouTube. CPM avg $18. Newsletter of 22K. Massive Q4 seasonality. 3 active sponsorship deals worth $3K+/month each.",                         seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-04T09:00:00Z", featured:false },
  { id:"listing-22", platform:"YouTube",   username:"TechReviewHub",      niche:"Tech",      followers:450000,  monthly_income:6200,  engagement_rate:4.9,  price:148800, minimum_offer:125000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Tech reviews and unboxings. Amazon Associates $1.2K/mo. Very loyal subscriber base. Avg view duration 8+ minutes. CPM $22.",                                  seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-13T11:00:00Z", featured:false },
  { id:"listing-23", platform:"YouTube",   username:"GamingWithPro",      niche:"Gaming",    followers:220000,  monthly_income:2800,  engagement_rate:6.7,  price:67200,  minimum_offer:56000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,  location:"Canada",        description:"Gaming channel. Let's Play and reviews. Growing 8K subs/month. Great demographics for gaming brands. AdSense + 2 sponsorship deals.",                          seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-20T16:00:00Z", featured:false },
  { id:"listing-24", platform:"YouTube",   username:"FoodLaboratory",     niche:"Food",      followers:890000,  monthly_income:9600,  engagement_rate:7.2,  price:230400, minimum_offer:195000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Food science and cooking. 890K subscribers. Very high CPM $16. HelloFresh and BlueApron sponsor history. 40M total views. Evergreen content.",                  seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-01T10:00:00Z", featured:false },
  { id:"listing-25", platform:"YouTube",   username:"WealthBuilderYT",    niche:"Finance",   followers:125000,  monthly_income:5800,  engagement_rate:5.3,  price:139200, minimum_offer:115000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Personal wealth and investing channel. CPM $22+. Credit card and investment app affiliate deals. 50K email newsletter included.",                             seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-08T12:00:00Z", featured:false },
  { id:"listing-26", platform:"YouTube",   username:"TravelSeeker",       niche:"Travel",    followers:340000,  monthly_income:4100,  engagement_rate:4.8,  price:98400,  minimum_offer:82000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Australia",     description:"Travel vlogs and destination guides. Hotel and airline sponsor history. Strong 28-45 demographic. Very high watch time (12min avg).",                           seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-15T13:00:00Z", featured:false },
  { id:"listing-27", platform:"YouTube",   username:"BeautySecrets101",   niche:"Beauty",    followers:560000,  monthly_income:7200,  engagement_rate:6.1,  price:172800, minimum_offer:145000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Beauty tutorials and reviews. 7 active brand partnerships. 80% female 18-35. Amazon storefront earning $2K/mo. Evergreen tutorial content.",                  seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-10T09:00:00Z", featured:false },
  { id:"listing-28", platform:"YouTube",   username:"SportsCentral",      niche:"Sports",    followers:275000,  monthly_income:3400,  engagement_rate:5.6,  price:81600,  minimum_offer:68000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,  location:"United Kingdom", description:"Sports analysis and highlights. Peak revenue during football season. Sportsbook affiliates $1.5K/mo. Strong 20-40 male UK audience.",                       seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-17T14:00:00Z", featured:false },
  { id:"listing-29", platform:"YouTube",   username:"MindfulnessDaily",   niche:"Lifestyle", followers:195000,  monthly_income:2600,  engagement_rate:4.4,  price:62400,  minimum_offer:52000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Mindfulness and wellness. Calm app affiliate deal ($800/mo). Online course sales $1K/mo. Very loyal, engaged audience with low churn.",                      seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-22T11:00:00Z", featured:false },
  // ── X ──────────────────────────────────────────────────────────────────────
  { id:"listing-30", platform:"X",         username:"@cryptoanalyst_x",   niche:"Crypto",    followers:125000,  monthly_income:3200,  engagement_rate:3.4,  price:76800,  minimum_offer:65000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:false, location:"United States", description:"Crypto analysis and alpha. Verified account. Paid newsletter 4K subscribers ($1.8K/mo). Exchange affiliate deals ($1.4K/mo). High-trust authority positioning.", seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-05T10:00:00Z", featured:false },
  { id:"listing-31", platform:"X",         username:"@techinsider_x",     niche:"Tech",      followers:89000,   monthly_income:1800,  engagement_rate:2.9,  price:43200,  minimum_offer:36000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"United States", description:"Tech news and commentary. Strong network with VCs and founders. Multiple publication relationships. Newsletter 3K subscribers.",                              seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-19T15:00:00Z", featured:false },
  { id:"listing-32", platform:"X",         username:"@sportsbreaking",    niche:"Sports",    followers:210000,  monthly_income:1400,  engagement_rate:4.2,  price:33600,  minimum_offer:28000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"United Kingdom", description:"Sports breaking news. Massive engagement during match days. Sportsbook sponsor history. Real-time transfer news exclusive scoops.",                          seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-14T12:00:00Z", featured:false },
  { id:"listing-33", platform:"X",         username:"@financetips_hq",    niche:"Finance",   followers:156000,  monthly_income:4200,  engagement_rate:3.8,  price:100800, minimum_offer:85000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Finance tips and stock picks. X Premium subscription revenue. Newsletter 6K subscribers. Very high-income audience perfect for wealth management ads.",        seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-07T09:00:00Z", featured:false },
  { id:"listing-34", platform:"X",         username:"@gamernews_x",       niche:"Gaming",    followers:78000,   monthly_income:900,   engagement_rate:5.1,  price:18000,  minimum_offer:15000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"Canada",        description:"Gaming industry news and leaks. Strong relationship with developers. Exclusive reveal potential. Highly engaged gaming enthusiast audience.",                   seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-24T11:00:00Z", featured:false },
  { id:"listing-35", platform:"X",         username:"@businessdaily_x",   niche:"Business",  followers:195000,  monthly_income:3600,  engagement_rate:3.3,  price:86400,  minimum_offer:72000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Business strategy and growth hacking. B2B SaaS sponsor deals $2.5K/mo. Newsletter 8K. Highly actionable content with strong founder/exec audience.",          seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-11T13:00:00Z", featured:false },
  // ── Telegram ───────────────────────────────────────────────────────────────
  { id:"listing-36", platform:"Telegram",  username:"CryptoSignalsPro",   niche:"Crypto",    followers:48000,   monthly_income:9600,  engagement_rate:12.0, price:230400, minimum_offer:195000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"UAE",           description:"Premium crypto signals. $200/mo subscription. 48K members, 1.2K paying ($240K ARR). Extremely high value recurring revenue. 4 years history.",                    seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-03T10:00:00Z", featured:false },
  { id:"listing-37", platform:"Telegram",  username:"TechNewsTG",         niche:"Tech",      followers:72000,   monthly_income:2400,  engagement_rate:8.5,  price:57600,  minimum_offer:48000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"Germany",       description:"Tech news Telegram. 72K members. Sponsored post rate $500. German market focus with high purchasing power audience.",                                           seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-20T09:00:00Z", featured:false },
  { id:"listing-38", platform:"Telegram",  username:"FinanceDaily_TG",    niche:"Finance",   followers:34000,   monthly_income:4200,  engagement_rate:9.8,  price:100800, minimum_offer:85000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Singapore",     description:"Finance and investing Telegram. 34K members. Subscription model $4.2K MRR. Highly profitable. Strong Southeast Asian audience.",                              seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-09T12:00:00Z", featured:false },
  { id:"listing-39", platform:"Telegram",  username:"FitnessAlerts",      niche:"Fitness",   followers:56000,   monthly_income:1800,  engagement_rate:7.2,  price:36000,  minimum_offer:30000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"United States", description:"Fitness tips and workout alerts. Daily content, very engaged community. Supplement affiliate potential. Growing 3K members/month.",                          seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-16T14:00:00Z", featured:false },
  { id:"listing-40", platform:"Telegram",  username:"GamingHub_TG",       niche:"Gaming",    followers:91000,   monthly_income:3200,  engagement_rate:11.4, price:64000,  minimum_offer:54000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Gaming deals and giveaways channel. 91K members. Sponsor deals $2.8K/mo. Game key affiliate $400/mo. Very high engagement rate.",                           seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-13T10:00:00Z", featured:false },
  // ── Additional variety ─────────────────────────────────────────────────────
  { id:"listing-41", platform:"TikTok",    username:"@musicvibes_hq",     niche:"Music",     followers:890000,  monthly_income:5600,  engagement_rate:12.3, price:112000, minimum_offer:94000,  status:"active", verified_income:true,  tiktok_shop_eligible:true,  monetized:true,  location:"United States", description:"Music discovery and artist promotion TikTok. 890K followers with viral sound history. Record label partnership potential. DSP affiliate deals.",              seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-04T11:00:00Z", featured:false },
  { id:"listing-42", platform:"Instagram", username:"@styleicon_daily",   niche:"Lifestyle", followers:680000,  monthly_income:6200,  engagement_rate:4.9,  price:148800, minimum_offer:125000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"Italy",         description:"Fashion and lifestyle. Italian luxury market. Versace and Armani sponsored posts. Shopping app affiliate $1.5K/mo. Premium 28-45 female demographic.",         seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-06T09:00:00Z", featured:false },
  { id:"listing-43", platform:"YouTube",   username:"BusinessGrowth101",  niche:"Business",  followers:410000,  monthly_income:7800,  engagement_rate:5.2,  price:187200, minimum_offer:157000, status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Business and entrepreneurship. B2B SaaS sponsors $3K/mo. Course sales platform $2K/mo. 410K very engaged founder/exec audience. CPM $28.",                 seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-02T10:00:00Z", featured:false },
  { id:"listing-44", platform:"TikTok",    username:"@crypto_calls_tk",   niche:"Crypto",    followers:330000,  monthly_income:4800,  engagement_rate:8.9,  price:96000,  minimum_offer:80000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"UAE",           description:"Crypto market calls and DeFi tutorials. Very high engagement. Exchange affiliate deals $3.2K/mo. Premium 25-35 male audience.",                              seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-18T13:00:00Z", featured:false },
  { id:"listing-45", platform:"X",         username:"@lifestylelux_x",    niche:"Lifestyle", followers:114000,  monthly_income:2200,  engagement_rate:4.6,  price:52800,  minimum_offer:44000,  status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false, location:"United States", description:"Luxury lifestyle content on X. Strong engagement from high-net-worth individuals. Watch and real estate sponsor potential.",                               seller_name:"SocialPro",   seller_id:"user-1", seller_rating:4.9, seller_sales:12, created_at:"2025-01-21T11:00:00Z", featured:false },
  { id:"listing-46", platform:"Telegram",  username:"SportsAlerts_TG",    niche:"Sports",    followers:124000,  monthly_income:3800,  engagement_rate:9.1,  price:76000,  minimum_offer:64000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United Kingdom", description:"Sports alerts and betting tips channel. 124K members. Sportsbook sponsor $2.8K/mo. Free picks + premium subscription model $1K/mo MRR.",              seller_name:"AccountKing", seller_id:"user-2", seller_rating:4.8, seller_sales:8,  created_at:"2025-01-12T09:00:00Z", featured:false },
  { id:"listing-47", platform:"Instagram", username:"@travelblogger_pro", niche:"Travel",    followers:410000,  monthly_income:3400,  engagement_rate:4.1,  price:81600,  minimum_offer:68000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Travel photography and destination guides. 3 hotel brand deals active. American Express travel affiliate $800/mo. Growing 8K followers/month.",              seller_name:"InfluenceHQ", seller_id:"user-3", seller_rating:5.0, seller_sales:23, created_at:"2025-01-14T15:00:00Z", featured:false },
  { id:"listing-48", platform:"YouTube",   username:"MusicProduction101", niche:"Music",     followers:280000,  monthly_income:3800,  engagement_rate:6.4,  price:91200,  minimum_offer:76000,  status:"active", verified_income:true,  tiktok_shop_eligible:false, monetized:true,  location:"United States", description:"Music production tutorials. Ableton and Native Instruments affiliate $1.2K/mo. Very loyal music producer audience. Course sales $1.8K/mo.",               seller_name:"GrowthLabs",  seller_id:"user-5", seller_rating:4.9, seller_sales:15, created_at:"2025-01-08T10:00:00Z", featured:false },
  { id:"listing-49", platform:"TikTok",    username:"@beautytrends_now",  niche:"Beauty",    followers:760000,  monthly_income:5800,  engagement_rate:10.8, price:116000, minimum_offer:97000,  status:"active", verified_income:true,  tiktok_shop_eligible:true,  monetized:true,  location:"South Korea",   description:"K-beauty trends and tutorials. Explosive 760K followers in 18 months. Korean beauty brand deal rates premium. TikTok Shop GMV $3K/mo. Global audience.",        seller_name:"MediaFlip",   seller_id:"user-4", seller_rating:4.7, seller_sales:6,  created_at:"2025-01-05T09:00:00Z", featured:false },
];

export const SEED_LISTINGS: Listing[] = LISTINGS_DATA.map((l) => ({
  ...l,
  gradient:   PLATFORM_GRADIENTS[l.platform],
  emoji:      PLATFORM_EMOJIS[l.platform],
  niche_emoji: NICHE_EMOJIS[l.niche],
}));

export const MARKETPLACE_STATS = {
  active_listings: 5214,
  total_volume:    14_200_000,
  avg_rating:      4.98,
  total_transfers: 3842,
};
